/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layoutCadastro;

import DAO.Conexao;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.net.URL;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import java.sql.*;
import javax.swing.JFileChooser;
import layoutInterno.buscaEmpresa;
import layoutInterno.buscaFornecedor;
import javax.swing.ButtonGroup;
/**
 *
 * @author Su
 */
public class frmCadFornecedor extends javax.swing.JFrame {

    /**
     * Creates new form frmCadFornecedor
     */
    Connection conec = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    String filename;
    String guardaFoto;
    int img = 0,verificaImg = 0;
    ButtonGroup objFisico,objJuridico;
    buscaFornecedor objBuscarForne;
    char status='S';
    public frmCadFornecedor() {
        initComponents();
        try {
            conec = Conexao.conecta();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmCadFornecedor.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frmCadFornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }
        objFisico = new ButtonGroup();
        objFisico.add(rbOnFisico);
        objFisico.add(rbOffFisico);
        objJuridico = new ButtonGroup();
        objJuridico.add(rbOnJuridico);
        objJuridico.add(rbOffJuridico);
        telefone();
         URL url = this.getClass().getResource("/imagens/IconePequeno.png");  
       Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);  
       this.setIconImage(iconeTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        lbFotoFisico = new javax.swing.JLabel();
        btnAlteraImagem = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtBuscaFisico = new javax.swing.JTextField();
        btnf8Busca = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnGravar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtCodigoFisico = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNomeFisico = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        rbOnFisico = new javax.swing.JCheckBox();
        rbOffFisico = new javax.swing.JCheckBox();
        txtTelefeFisic = new javax.swing.JFormattedTextField();
        txtCPF = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        txtCelularFisi = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        txtEnderecoFisico = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtBairroFisico = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtCepFisico = new javax.swing.JFormattedTextField();
        jPanel5 = new javax.swing.JPanel();
        lbFotoJuridico = new javax.swing.JLabel();
        btnAlteraImagem1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtBuscaJuridico = new javax.swing.JTextField();
        btnf8Busca1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNomeJuridico = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCelularJuridi = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        txtEnderecoJuridico = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtBairroJuridico = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtCepJuridico = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnGravar1 = new javax.swing.JButton();
        btnEditar1 = new javax.swing.JButton();
        btnLimpar1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        rbOnJuridico = new javax.swing.JCheckBox();
        rbOffJuridico = new javax.swing.JCheckBox();
        txtCodigoJuridico = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtTelefoneJurid = new javax.swing.JFormattedTextField();
        txtCnpj = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Fornecedor");

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbFotoFisico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/semFoto.png"))); // NOI18N
        jPanel4.add(lbFotoFisico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        btnAlteraImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Edit Image-16.png"))); // NOI18N
        btnAlteraImagem.setText("Alterar Img");
        btnAlteraImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlteraImagemActionPerformed(evt);
            }
        });
        jPanel4.add(btnAlteraImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 154, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Codigo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 17, -1, -1));
        jPanel1.add(txtBuscaFisico, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 14, 264, -1));

        btnf8Busca.setText("F8");
        btnf8Busca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnf8BuscaActionPerformed(evt);
            }
        });
        jPanel1.add(btnf8Busca, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 13, 57, -1));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 11, 383, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Save-16.png"))); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Edit Property-16.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Eraser-16.png"))); // NOI18N
        btnLimpar.setText("limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        jButton1.setText("Deletar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGravar)
                .addGap(18, 18, 18)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGravar)
                    .addComponent(btnEditar)
                    .addComponent(btnLimpar)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 268, 370, -1));

        jLabel3.setText("Codigo");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 74, -1, -1));

        txtCodigoFisico.setEditable(false);
        txtCodigoFisico.setBackground(new java.awt.Color(153, 153, 153));
        txtCodigoFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoFisicoActionPerformed(evt);
            }
        });
        jPanel4.add(txtCodigoFisico, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 71, 330, -1));

        jLabel4.setText("Nome");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 100, -1, -1));
        jPanel4.add(txtNomeFisico, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 97, 330, -1));

        jLabel5.setText("Telefone");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 123, -1, -1));

        jLabel6.setText("CPF:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 209, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rbOnFisico.setText("Ativo");
        jPanel3.add(rbOnFisico, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 9, -1, -1));

        rbOffFisico.setText("Desativado");
        jPanel3.add(rbOffFisico, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 9, -1, -1));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 268, 180, -1));
        jPanel4.add(txtTelefeFisic, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 123, 130, -1));
        jPanel4.add(txtCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 206, 161, -1));

        jLabel16.setText("Celular:");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 126, -1, -1));
        jPanel4.add(txtCelularFisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 123, 150, -1));

        jLabel17.setText("Endereço");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 152, -1, -1));
        jPanel4.add(txtEnderecoFisico, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 149, 330, -1));

        jLabel18.setText("Bairro");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 183, -1, -1));
        jPanel4.add(txtBairroFisico, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 180, 330, -1));

        jLabel19.setText("CEP");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 209, -1, -1));

        try {
            txtCepFisico.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel4.add(txtCepFisico, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 209, 130, -1));

        jTabbedPane1.addTab("Pessoa Fisica", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbFotoJuridico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/semFoto.png"))); // NOI18N
        jPanel5.add(lbFotoJuridico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        btnAlteraImagem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Edit Image-16.png"))); // NOI18N
        btnAlteraImagem1.setText("Alterar Img");
        btnAlteraImagem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlteraImagem1ActionPerformed(evt);
            }
        });
        jPanel5.add(btnAlteraImagem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 154, -1, -1));

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("Codigo");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 17, -1, -1));
        jPanel6.add(txtBuscaJuridico, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 14, 264, -1));

        btnf8Busca1.setText("F8");
        btnf8Busca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnf8Busca1ActionPerformed(evt);
            }
        });
        jPanel6.add(btnf8Busca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 13, 57, -1));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 11, 384, -1));

        jLabel1.setText("Nome");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 100, -1, -1));
        jPanel5.add(txtNomeJuridico, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 97, 330, -1));

        jLabel9.setText("Telefone");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 123, -1, -1));

        jLabel10.setText("Celular");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 126, -1, -1));

        try {
            txtCelularJuridi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCelularJuridi.setText("");
        jPanel5.add(txtCelularJuridi, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 123, 150, -1));

        jLabel11.setText("Endereço");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 152, -1, -1));
        jPanel5.add(txtEnderecoJuridico, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 149, 330, -1));

        jLabel12.setText("Bairro");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 183, -1, -1));
        jPanel5.add(txtBairroJuridico, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 180, 330, -1));

        jLabel13.setText("CEP");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 209, -1, -1));

        try {
            txtCepJuridico.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel5.add(txtCepJuridico, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 209, 130, -1));

        jLabel14.setText("CNPJ:");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 209, -1, -1));

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnGravar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Save-16.png"))); // NOI18N
        btnGravar1.setText("Gravar");
        btnGravar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravar1ActionPerformed(evt);
            }
        });

        btnEditar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Edit Property-16.png"))); // NOI18N
        btnEditar1.setText("Editar");
        btnEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar1ActionPerformed(evt);
            }
        });

        btnLimpar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Eraser-16.png"))); // NOI18N
        btnLimpar1.setText("limpar");
        btnLimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpar1ActionPerformed(evt);
            }
        });

        jButton2.setText("Deletar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGravar1)
                .addGap(18, 18, 18)
                .addComponent(btnEditar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLimpar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGravar1)
                    .addComponent(btnEditar1)
                    .addComponent(btnLimpar1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 268, 370, -1));

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rbOnJuridico.setText("Ativo");
        jPanel8.add(rbOnJuridico, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 9, -1, -1));

        rbOffJuridico.setText("Desativado");
        jPanel8.add(rbOffJuridico, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 9, -1, -1));

        jPanel5.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 268, 180, 51));

        txtCodigoJuridico.setEditable(false);
        txtCodigoJuridico.setBackground(new java.awt.Color(153, 153, 153));
        txtCodigoJuridico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoJuridicoActionPerformed(evt);
            }
        });
        jPanel5.add(txtCodigoJuridico, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 71, 330, -1));

        jLabel15.setText("Codigo");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 74, -1, -1));
        jPanel5.add(txtTelefoneJurid, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 123, 130, -1));
        jPanel5.add(txtCnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 206, 161, -1));

        jTabbedPane1.addTab("Pessoa Juridica", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlteraImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlteraImagemActionPerformed
        verificaImg += 1;
        JFileChooser foto = new JFileChooser();
        foto.setDialogTitle("Selecione a Imagem");
        foto.setFileSelectionMode(JFileChooser.FILES_ONLY);

        int opc = foto.showOpenDialog(this);
        if (opc == JFileChooser.APPROVE_OPTION) {
            File file = new File("caminho");
            file = foto.getSelectedFile();
            filename = file.getAbsolutePath();

            ImageIcon images = new ImageIcon(foto.getSelectedFile().getPath());
            lbFotoFisico.setIcon(new ImageIcon(images.getImage().getScaledInstance(lbFotoFisico.getWidth(), lbFotoFisico.getHeight(), Image.SCALE_DEFAULT)));
            img = 1;
        } else {
            img = 0;
            filename = "foto/semFoto.png";
        }
    }//GEN-LAST:event_btnAlteraImagemActionPerformed

    private void btnf8BuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf8BuscaActionPerformed
  try {
            objBuscarForne = new buscaFornecedor(this, rootPaneCheckingEnabled);
            objBuscarForne.setLocationRelativeTo(null);
            objBuscarForne.setVisible(true);
            if(objBuscarForne.getNomeFisico().equals("")){
            }else{
                 ColetaDadosFisico();  
            }
       } catch (SQLException ex) {
            Logger.getLogger(frmCadFornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }       
     
    }//GEN-LAST:event_btnf8BuscaActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        if (img == 0) {
            filename = "foto/semFoto.png";
        }
        TratamentoFisico(1);
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        TratamentoFisico(2);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparCamposFisico();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtCodigoFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoFisicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoFisicoActionPerformed

    private void btnAlteraImagem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlteraImagem1ActionPerformed
        JFileChooser foto = new JFileChooser();
        foto.setDialogTitle("Selecione a Imagem");
        foto.setFileSelectionMode(JFileChooser.FILES_ONLY);

        int opc = foto.showOpenDialog(this);
        if (opc == JFileChooser.APPROVE_OPTION) {
            File file = new File("caminho");
            file = foto.getSelectedFile();
            filename = file.getAbsolutePath();

            ImageIcon images = new ImageIcon(foto.getSelectedFile().getPath());
            lbFotoJuridico.setIcon(new ImageIcon(images.getImage().getScaledInstance(lbFotoJuridico.getWidth(), lbFotoJuridico.getHeight(), Image.SCALE_DEFAULT)));
            img = 1;

        } else {
            img = 0;
            filename = "foto/semFoto.png";
        }
    }//GEN-LAST:event_btnAlteraImagem1ActionPerformed

    private void btnf8Busca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf8Busca1ActionPerformed
       try {
            objBuscarForne = new buscaFornecedor(this, rootPaneCheckingEnabled);
            objBuscarForne.setLocationRelativeTo(null);
            objBuscarForne.setVisible(true);
            if(objBuscarForne.getNomeJuridico().equals("")){
            }else{
              ColetaDadosJuridico();
            }
       } catch (SQLException ex) {
            Logger.getLogger(frmCadFornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }
        
            
        
    }//GEN-LAST:event_btnf8Busca1ActionPerformed

    private void btnGravar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravar1ActionPerformed
        TratamentoJuridico(1);
    }//GEN-LAST:event_btnGravar1ActionPerformed

    private void btnEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar1ActionPerformed
        TratamentoJuridico(2);
    }//GEN-LAST:event_btnEditar1ActionPerformed

    private void btnLimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpar1ActionPerformed
limparCamposJuridico();
    }//GEN-LAST:event_btnLimpar1ActionPerformed

    private void txtCodigoJuridicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoJuridicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoJuridicoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       DeletarFisico();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     DeletarJuridico();
    }//GEN-LAST:event_jButton2ActionPerformed
  private void ColetaDadosJuridico(){
   txtCodigoJuridico.setText(""+objBuscarForne.getCodigoJuridico());
   txtNomeJuridico.setText(objBuscarForne.getNomeJuridico());
   txtTelefoneJurid.setText(objBuscarForne.getTelJuridico());
   txtCelularJuridi.setText(objBuscarForne.getCelJuridico());
   txtEnderecoJuridico.setText(objBuscarForne.getEnderecoJuridico());
   txtBairroJuridico.setText(objBuscarForne.getBairroJuridico());
   txtCepJuridico.setText(objBuscarForne.getCepJuridico());
   txtCnpj.setText(objBuscarForne.getCnpj());
   if(objBuscarForne.getStatusJuridico().equals("S")){
  rbOnJuridico.setSelected(true);
   }else{
   rbOffJuridico.setSelected(true);
   }
   if(objBuscarForne.getImgJuridico().equals("/foto/semFoto.png") || objBuscarForne.getImgJuridico().equals("")){
    ImageIcon imgPadrao = new ImageIcon(getClass().getResource("/foto/semFoto.png"));
    lbFotoJuridico.setIcon(imgPadrao);
   }else{
   ImageIcon imgPadrao = new ImageIcon(objBuscarForne.getImgJuridico());
   lbFotoJuridico.setIcon(new ImageIcon(imgPadrao.getImage().getScaledInstance(135,137,Image.SCALE_DEFAULT)));
   }
   }
    private void ColetaDadosFisico(){
  txtCodigoFisico.setText(""+objBuscarForne.getCodigoFisico());
   txtNomeFisico.setText(objBuscarForne.getNomeFisico());
   txtTelefeFisic.setText(objBuscarForne.getTelFisico());
   txtCelularFisi.setText(""+objBuscarForne.getCelFisico());
   txtEnderecoFisico.setText(objBuscarForne.getEnderecoFisico());
   txtBairroFisico.setText(objBuscarForne.getBairroFisico());
   txtCepFisico.setText(objBuscarForne.getCepFisico());
   txtCPF.setText(objBuscarForne.getCpf());
   if(objBuscarForne.getStatusFisico().equals("S")){
  rbOnFisico.setSelected(true);
   }else{
   rbOffFisico.setSelected(true);
   }
   if(objBuscarForne.getImgFisico().equals("foto/semFoto.png")){
    ImageIcon imgPadrao = new ImageIcon(getClass().getResource("/foto/semFoto.png"));
    lbFotoFisico.setIcon(imgPadrao);
   }else{
   ImageIcon imgPadrao = new ImageIcon(objBuscarForne.getImgFisico());
   lbFotoFisico.setIcon(new ImageIcon(imgPadrao.getImage().getScaledInstance(lbFotoFisico.getWidth(),lbFotoFisico.getHeight(),Image.SCALE_DEFAULT)));
   }
   }
    protected void TratamentoFisico(int troll){
  if(txtNomeFisico.getText().equals("")){
  JOptionPane.showMessageDialog(null,"Campo Nome vazio!","Aviso",JOptionPane.INFORMATION_MESSAGE);
  }else{
  switch(troll){
      case 1:
         cadastrarFisica();
         limparCamposFisico();
         break;
      case 2:
          if(txtCodigoFisico.getText().equals("")){
          JOptionPane.showMessageDialog(null,"Campo Codigo vazio!","Aviso",JOptionPane.INFORMATION_MESSAGE);
          }else{
          EditarFisico();
          limparCamposFisico();
          }
          break;
  }
  }
  }
     protected void TratamentoJuridico(int troll){
  if(txtNomeJuridico.getText().equals("")){
  JOptionPane.showMessageDialog(null,"Campo Nome vazio!","Aviso",JOptionPane.INFORMATION_MESSAGE);
  }else{
  switch(troll){
      case 1:
         cadastrarJuridico();
         limparCamposJuridico();
         break;
      case 2:
          if(txtCodigoJuridico.getText().equals("")){
          JOptionPane.showMessageDialog(null,"Campo Codigo vazio!","Aviso",JOptionPane.INFORMATION_MESSAGE);
          }else{
          EditarJuridico();
          limparCamposJuridico();
          }
          break;
  }
  }
  }
    public void cadastrarFisica(){
        String sql = "insert into fornecedorfisico(nome,telefone,celular,cpf,endereco,bairro,cep,img)\n" +
"values(?,?,?,?,?,?,?,?)";
       try {
            pst = conec.prepareStatement(sql);
            pst.setString(1, txtNomeFisico.getText());
            pst.setString(2, txtTelefeFisic.getText().replace("(", "").replace(")", "").replace("-", ""));
            pst.setString(3,txtCelularFisi.getText().replace("(", "").replace(")", "").replace("-", ""));
            pst.setString(4, txtCPF.getText().replace(".","").replace(".","").replace("-",""));
            pst.setString(5, txtEnderecoFisico.getText());
            pst.setString(6,txtBairroFisico.getText());
            pst.setString(7,txtCepFisico.getText().replace("-",""));
            if(filename.equals("")){
            filename = "/foto/semFoto.png";
            }
            pst.setString(8,filename);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Fornecedor Fisico Cadastrado", "Fornecedor Cadastrado", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException error) {
            JOptionPane.showMessageDialog(null, error);
        }
    }

    private void EditarFisico() {
         if(img == 0){
            pegarImgAntesEditar(Integer.parseInt(txtCodigoFisico.getText()));
            }
         if(rbOnFisico.isSelected()){
            status = 'S';
            }else if(rbOffFisico.isSelected()){
            status = 'N';
            }else{
            status = 'S';
            }
         String sql = "update fornecedorfisico set nome=?,telefone=?,celular=?,cpf=?,endereco=?,bairro=?,cep=?,img=?,status=? where idfornefisico = ?";
       try {
            pst = conec.prepareStatement(sql);
            pst.setString(1, txtNomeFisico.getText());
            pst.setString(2, txtTelefeFisic.getText().replace("(", "").replace(")", "").replace("-", ""));
            pst.setString(3,txtCelularFisi.getText().replace("(", "").replace(")", "").replace("-", ""));
            pst.setString(4, txtCPF.getText().replace(".","").replace(".","").replace("-",""));
            pst.setString(5, txtEnderecoFisico.getText());
            pst.setString(6,txtBairroFisico.getText());
            pst.setString(7,txtCepFisico.getText().replace("-",""));
            pst.setString(8,filename);
            pst.setString(9,String.valueOf(status));
            pst.setInt(10,Integer.parseInt(txtCodigoFisico.getText()));
            if(pst.executeUpdate() >0){
            JOptionPane.showMessageDialog(null, "Fornecedor Fisico Atualizado", "Fornecedor Atualizado", JOptionPane.INFORMATION_MESSAGE);
            }
            } catch (SQLException error) {
            JOptionPane.showMessageDialog(null, error);
        }
    }
     public void cadastrarJuridico(){
        String sql = "insert into fornecedorjuridico(nome,telefone,celular,endereco,bairro,cep,cnpj,img)\n" +
"values(?,?,?,?,?,?,?,?)";
       try {
            pst = conec.prepareStatement(sql);
            pst.setString(1, txtNomeJuridico.getText());
            pst.setString(2, txtTelefoneJurid.getText().replace("(", "").replace(")", "").replace("-", ""));
            pst.setString(3,txtCelularJuridi.getText().replace("(", "").replace(")", "").replace("-", ""));
            pst.setString(4, txtEnderecoJuridico.getText());
            pst.setString(5,txtBairroJuridico.getText());
            pst.setString(6,txtCepJuridico.getText().replace("-",""));
            pst.setString(7, txtCnpj.getText().replace(".","").replace(".","").replace("/","").replace("-",""));
            if(img == 0){
            filename = "/foto/semFoto.png";
            }
            pst.setString(8,filename);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Fornecedor Juridico Cadastrado", "Fornecedor Cadastrado", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException error) {
            JOptionPane.showMessageDialog(null, error);
        }
    }
     private void EditarJuridico() {
          if(img == 0){
            pegarImgAntesEditarJuridico(Integer.parseInt(txtCodigoJuridico.getText()));
            }
         if(rbOnJuridico.isSelected()){
            status = 'S';
            }else if(rbOffJuridico.isSelected()){
            status = 'N';
            }else{
            status = 'S';
            }
         String sql = "update fornecedorjuridico set nome=?,telefone=?,celular=?,endereco=?,bairro=?,cep=?,cnpj=?,img=?,status=? where idfornjuridico=?";
          try {
            pst = conec.prepareStatement(sql);
            pst.setString(1,txtNomeJuridico.getText());
            pst.setString(2,txtTelefoneJurid.getText().replace("(", "").replace(")", "").replace("-", ""));
            pst.setString(3,txtCelularJuridi.getText().replace("(", "").replace(")", "").replace("-", ""));
            pst.setString(4,txtEnderecoJuridico.getText());
            pst.setString(5,txtBairroJuridico.getText());
            pst.setString(6,txtCepJuridico.getText().replace("-",""));
            pst.setString(7,txtCnpj.getText().replace(".","").replace(".","").replace("/","").replace("-",""));
            pst.setString(8,filename);
            pst.setString(9,String.valueOf(status));
            pst.setInt(10,Integer.parseInt(txtCodigoJuridico.getText()));
            if(pst.executeUpdate() > 0){
            JOptionPane.showMessageDialog(null, "Fornecedor Juridico Atualizado", "Fornecedor Atualizado", JOptionPane.INFORMATION_MESSAGE);
            }
            } catch (SQLException error) {
            JOptionPane.showMessageDialog(null, error.getMessage(),"Aviso",JOptionPane.ERROR_MESSAGE);
        }
     }
    public void pegarImgAntesEditar(int pk){
    try{
    pst = conec.prepareStatement(" select img from fornecedorfisico where idfornefisico =?");
    pst.setInt(1,pk);
    rs = pst.executeQuery();
    if(rs.next()){
    filename = rs.getString(1);
    }
    }catch(SQLException e){
    JOptionPane.showMessageDialog(null,e.getMessage(),"Aviso",JOptionPane.ERROR_MESSAGE);
    }
    }
     public void pegarImgAntesEditarJuridico(int pk){
    try{
    pst = conec.prepareStatement(" select img from fornecedorjuridico where idfornjuridico = ?");
    pst.setInt(1,pk);
    rs = pst.executeQuery();
    if(rs.next()){
    filename = rs.getString(1);
    }
    }catch(SQLException e){
    JOptionPane.showMessageDialog(null,e.getMessage(),"Aviso",JOptionPane.ERROR_MESSAGE);
    }
    }
  
    
    private void limparCamposFisico() {
        txtBuscaFisico.setText("");
         txtCodigoFisico.setText("");
        txtNomeFisico.setText("");
        txtTelefeFisic.setText("");
        txtCelularFisi.setText("");
        txtEnderecoFisico.setText("");
        txtBairroFisico.setText("");
        txtCepFisico.setText("");
        txtCPF.setText("");
        objFisico.clearSelection();
        filename="";
        ImageIcon IMGpadrao = new ImageIcon(this.getClass().getResource("/foto/semFoto.png"));
        lbFotoFisico.setIcon(new ImageIcon(IMGpadrao.getImage().getScaledInstance(lbFotoFisico.getWidth(), lbFotoFisico.getHeight(), Image.SCALE_DEFAULT)));
        txtNomeFisico.requestFocus();
        img=0;
    }
private void limparCamposJuridico() {
        txtBuscaJuridico.setText("");
         txtCodigoJuridico.setText("");
        txtNomeJuridico.setText("");
        txtTelefoneJurid.setText("");
        txtCelularJuridi.setText("");
        txtEnderecoJuridico.setText("");
        txtBairroJuridico.setText("");
        txtCepJuridico.setText("");
        txtCnpj.setText("");
        objJuridico.clearSelection();
         filename="";
        ImageIcon IMGpadrao = new ImageIcon(this.getClass().getResource("/foto/semFoto.png"));
        lbFotoJuridico.setIcon(new ImageIcon(IMGpadrao.getImage().getScaledInstance(lbFotoFisico.getWidth(), lbFotoFisico.getHeight(), Image.SCALE_DEFAULT)));
        img=0;    
}
    private void telefone() {

        MaskFormatter mascaraTelefoneFisica,mascaraTelefoneJuridica,mascaraCelularJuridico,mascaraCelularFisico;
        MaskFormatter mascaraCNPJ,mascaraCPF,mascaraCEPFisico,mascaraCEPJuridico;
        try {
            mascaraTelefoneFisica = new MaskFormatter("(##)####-####");
            mascaraTelefoneFisica.setValidCharacters("0123456789");
            mascaraTelefoneFisica.install(txtTelefeFisic);
            //
            mascaraTelefoneJuridica = new MaskFormatter("(##)####-####");
            mascaraTelefoneJuridica.setValidCharacters("0123456789");
            mascaraTelefoneJuridica.install(txtTelefoneJurid);
            //
            mascaraCelularFisico = new MaskFormatter("(##)#####-####");
            mascaraCelularFisico.setValidCharacters("0123456789");
            mascaraCelularFisico.install(txtCelularFisi);
            //
            mascaraCelularJuridico = new MaskFormatter("(##)#####-####");
            mascaraCelularJuridico.setValidCharacters("0123456789");
            mascaraCelularJuridico.install(txtCelularJuridi);
            //--
            mascaraCEPFisico = new MaskFormatter("#####-###");
            mascaraCEPFisico.setValidCharacters("0123456789");
            mascaraCEPFisico.install(txtCepFisico);
            //
            mascaraCEPJuridico = new MaskFormatter("#####-###");
            mascaraCEPJuridico.setValidCharacters("0123456789");
            mascaraCEPJuridico.install(txtCepJuridico);
            //
            mascaraCPF = new MaskFormatter("###.###.###-##");
            mascaraCPF.setValidCharacters("0123456789");
            mascaraCPF.install(txtCPF);
            //
            mascaraCNPJ = new MaskFormatter("##.###.###/####-##");
            mascaraCNPJ.setValidCharacters("0123456789");
            mascaraCNPJ.install(txtCnpj);
        } catch (Exception ex) {
            Logger.getLogger(frmCadFornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    private void buscaImagem (){
        
        try {
            pst = conec.prepareStatement("select foto from fornecedor where id_fornecedor = ?");
            pst.setInt(1, Integer.parseInt(txtCodigoFisico.getText()));
            rs = pst.executeQuery();
            if(rs.next()){
                filename = String.valueOf(rs.getString(1));
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(cadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void DeletarJuridico(){
    if(JOptionPane.showConfirmDialog(null,"Deletar Fornecedor Juridico(Empresa)","Aviso",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE) == JOptionPane.YES_OPTION){
    try{
    pst= conec.prepareStatement("delete from fornecedorjuridico where idfornjuridico = ?");
    pst.setInt(1,Integer.parseInt(txtCodigoJuridico.getText()));
    if(pst.executeUpdate() > 0){
    JOptionPane.showMessageDialog(null,"Fornecedor Juridico(Empresa) Deletado");
    limparCamposJuridico();
    }
    }catch(SQLException error){
    JOptionPane.showMessageDialog(null,error.getMessage(),"Aviso",JOptionPane.ERROR_MESSAGE);
    }
    }
    }
    public void DeletarFisico(){
    if(JOptionPane.showConfirmDialog(null,"Deletar Fornecedor Fisico(Pessoa)","Aviso",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE) == JOptionPane.YES_OPTION){
    try{
    pst= conec.prepareStatement("delete from fornecedorfisico where idfornefisico = ?");
    pst.setInt(1,Integer.parseInt(txtCodigoFisico.getText()));
    if(pst.executeUpdate() > 0){
    JOptionPane.showMessageDialog(null,"Fornecedor Fisico(Pessoa) Deletado");
        limparCamposFisico();
    }
    }catch(SQLException error){
    JOptionPane.showMessageDialog(null,error.getMessage(),"Aviso",JOptionPane.ERROR_MESSAGE);
    }
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCadFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCadFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCadFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCadFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCadFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlteraImagem;
    private javax.swing.JButton btnAlteraImagem1;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEditar1;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnGravar1;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnLimpar1;
    private javax.swing.JButton btnf8Busca;
    private javax.swing.JButton btnf8Busca1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbFotoFisico;
    private javax.swing.JLabel lbFotoJuridico;
    private javax.swing.JCheckBox rbOffFisico;
    private javax.swing.JCheckBox rbOffJuridico;
    private javax.swing.JCheckBox rbOnFisico;
    private javax.swing.JCheckBox rbOnJuridico;
    private javax.swing.JTextField txtBairroFisico;
    private javax.swing.JTextField txtBairroJuridico;
    private javax.swing.JTextField txtBuscaFisico;
    private javax.swing.JTextField txtBuscaJuridico;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JFormattedTextField txtCelularFisi;
    private javax.swing.JFormattedTextField txtCelularJuridi;
    private javax.swing.JFormattedTextField txtCepFisico;
    private javax.swing.JFormattedTextField txtCepJuridico;
    private javax.swing.JFormattedTextField txtCnpj;
    private javax.swing.JTextField txtCodigoFisico;
    private javax.swing.JTextField txtCodigoJuridico;
    private javax.swing.JTextField txtEnderecoFisico;
    private javax.swing.JTextField txtEnderecoJuridico;
    private javax.swing.JTextField txtNomeFisico;
    private javax.swing.JTextField txtNomeJuridico;
    private javax.swing.JFormattedTextField txtTelefeFisic;
    private javax.swing.JFormattedTextField txtTelefoneJurid;
    // End of variables declaration//GEN-END:variables
}
