/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layoutInterno;

import DAO.Conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author Su
 */
public class frmBuscarForneFisico extends javax.swing.JDialog {
    Connection conec = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    private int codigoFisico;
    private String  nomeFisico;
    private String  telFisico;
    private String  celFisico;
    private String  cpf,cnpj,cepFisico;
    private String enderecoFisico;
    private String bairroFisico;
    private String statusFisico;
    private String imgFisico;
    /**
     * Creates new form frmBuscarForneFisico
     */
    
    public frmBuscarForneFisico(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try {
            conec = Conexao.conecta();
            PreencherTabelaFisico();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(buscaEmpresa.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frmBuscarForneFisico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscaFisica = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbFisica = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtForneceFisi = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar fornecedor fisico");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Pesquisar pelo nome do fornecedor fisico");

        txtBuscaFisica.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaFisicaKeyReleased(evt);
            }
        });

        tbFisica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbFisica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbFisicaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbFisica);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Fornecedor fsisico selecionado");

        txtForneceFisi.setEditable(false);
        txtForneceFisi.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(txtBuscaFisica)
                    .addComponent(txtForneceFisi))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscaFisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtForneceFisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 340));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/novoIcones/selecionarMenu.png"))); // NOI18N
        jMenu1.setText("Selecionar fornecedor fisico");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/novoIcones/sairMenu.png"))); // NOI18N
        jMenu2.setText("Sair");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscaFisicaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaFisicaKeyReleased
        if(getTxtBuscaFisica().getText().equals("")){
            PreencherTabelaFisico();
        }else{
            PreencherTabelaFisicoDigita();
        }
    }//GEN-LAST:event_txtBuscaFisicaKeyReleased

    private void tbFisicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbFisicaMouseClicked
            int linha_select = tbFisica.getSelectedRow();
            // cod_produto = (int) jTable1.getValueAt(linha_select, 0);
            codigoFisico = (Integer.parseInt((String) tbFisica.getValueAt(linha_select, 0).toString()));
            nomeFisico = (String) tbFisica.getValueAt(linha_select, 1);
            telFisico = (String) tbFisica.getValueAt(linha_select, 2);
            celFisico = (String) tbFisica.getValueAt(linha_select, 3);
            cpf =  tbFisica.getValueAt(linha_select, 4).toString();
            enderecoFisico = (String) tbFisica.getValueAt(linha_select, 5);
            bairroFisico = (String) tbFisica.getValueAt(linha_select, 6);
            cepFisico = tbFisica.getValueAt(linha_select, 7).toString();
            imgFisico = (String) tbFisica.getValueAt(linha_select, 8);
            statusFisico = (String) tbFisica.getValueAt(linha_select, 9);
            txtForneceFisi.setText(nomeFisico);
    }//GEN-LAST:event_tbFisicaMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
         if(getNomeFisico().equals("")){
            JOptionPane.showMessageDialog(null,"Selecione o fornecedor","Aviso",JOptionPane.INFORMATION_MESSAGE);
        }else{
            PreencherTabelaFisico();
            dispose();
        }
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
            PreencherTabelaFisico();
        RetornaVazio();
        dispose();
    }//GEN-LAST:event_jMenu2MouseClicked
 public void RetornaVazio(){
    codigoFisico=0;
    nomeFisico="";
    telFisico="";
    celFisico="";
    cpf="";
    cnpj="";
    cepFisico="";
    enderecoFisico="";
    bairroFisico="";
    statusFisico="";
    imgFisico="";
    }
    public void PreencherTabelaFisico() {
           String sql = ("select * from fornecedorfisico order by idfornefisico asc");
        try {
            pst = conec.prepareStatement(sql);
            rs = pst.executeQuery();
             tbFisica.setModel(DbUtils.resultSetToTableModel(rs));
            /*while (rs.next()){
                modelo.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10)});
            }*/
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar a Tabela Fisica " + erro,"Aviso",JOptionPane.ERROR_MESSAGE);
        }
    }
  public void PreencherTabelaFisicoDigita() {
           String sql = ("select * from fornecedorfisico where nome like ?");
        try {
            pst = conec.prepareStatement(sql);
            pst.setString(1,txtBuscaFisica.getText()+"%");
            rs = pst.executeQuery();
            tbFisica.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar a Tabela Fisica " + erro,"Aviso",JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBuscarForneFisico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBuscarForneFisico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBuscarForneFisico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBuscarForneFisico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmBuscarForneFisico dialog = new frmBuscarForneFisico(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbFisica;
    private javax.swing.JTextField txtBuscaFisica;
    private javax.swing.JTextField txtForneceFisi;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the codigoFisico
     */
    public int getCodigoFisico() {
        return codigoFisico;
    }

    /**
     * @return the nomeFisico
     */
    public String getNomeFisico() {
        return nomeFisico;
    }

    /**
     * @return the telFisico
     */
    public String getTelFisico() {
        return telFisico;
    }

    /**
     * @return the celFisico
     */
    public String getCelFisico() {
        return celFisico;
    }

    /**
     * @return the cpf
     */
    public String getCpf() {
        return cpf;
    }

    /**
     * @return the cnpj
     */
    public String getCnpj() {
        return cnpj;
    }

    /**
     * @return the cepFisico
     */
    public String getCepFisico() {
        return cepFisico;
    }

    /**
     * @return the enderecoFisico
     */
    public String getEnderecoFisico() {
        return enderecoFisico;
    }

    /**
     * @return the bairroFisico
     */
    public String getBairroFisico() {
        return bairroFisico;
    }

    /**
     * @return the statusFisico
     */
    public String getStatusFisico() {
        return statusFisico;
    }

    /**
     * @return the imgFisico
     */
    public String getImgFisico() {
        return imgFisico;
    }



    /**
     * @return the jLabel1
     */
    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    /**
     * @return the jLabel2
     */
    public javax.swing.JLabel getjLabel2() {
        return jLabel2;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @return the jTextField1
     */
    public javax.swing.JTextField getjTextField1() {
        return txtForneceFisi;
    }

    /**
     * @return the tbFisica
     */
    public javax.swing.JTable getTbFisica() {
        return tbFisica;
    }

    /**
     * @return the txtBuscaFisica
     */
    public javax.swing.JTextField getTxtBuscaFisica() {
        return txtBuscaFisica;
    }
}
