/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layout;

import DAO.Conexao;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Su
 */
public class VendaDiaria extends javax.swing.JDialog {

    /**
     * Creates new form VendaDiaria
     */
     Connection conec = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    private Date ant, depois;
    String hoje;
    public VendaDiaria(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try{
        initComponents();
         conec = Conexao.conecta();
         BuscarTodasVendas();
         BuscarTodasProdutosVendidos();
         BuscarQuantidadeTodasVendas();
         BuscarTotalTodasVendas();
        }catch(SQLException ex){
            Logger.getLogger(telaRelatorios.class.getName()).log(Level.SEVERE, null, ex);
        }catch(ClassNotFoundException ex){
             Logger.getLogger(VendaDiaria.class.getName()).log(Level.SEVERE, null, ex);
         }
         URL url = this.getClass().getResource("/imagens/IconePequeno.png");  
       Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);  
       this.setIconImage(iconeTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbVendas = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jDateInicial = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jDateFinal = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbProdutosVendidos = new javax.swing.JTable();
        lblQuantidadeVendaRegistrada = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTotalVenda = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lblTotalVendasRegistraPesquisa = new javax.swing.JLabel();
        lblValorTotalVendaPesquisa = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Venda Diaria");

        tbVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbVendas);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("ate");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Pesuisar data:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Search-20.png"))); // NOI18N
        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Cancel-16.png"))); // NOI18N
        jButton2.setText("Limpar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(0, 86, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jDateInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)
                                .addComponent(jDateFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9))
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Tela de venda", jPanel1);

        tbProdutosVendidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbProdutosVendidos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Produtos Vendidos", jPanel2);

        lblQuantidadeVendaRegistrada.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblQuantidadeVendaRegistrada.setText("0");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Total de vendas registradas:");

        lblTotalVenda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotalVenda.setText("0");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Valor total em vendas:");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informação da pesquisa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Total de vendas registradas:");

        lblTotalVendasRegistraPesquisa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotalVendasRegistraPesquisa.setText("0");

        lblValorTotalVendaPesquisa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblValorTotalVendaPesquisa.setText("0");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Valor total em vendas:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblValorTotalVendaPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(213, 213, 213)
                            .addComponent(lblTotalVendasRegistraPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(0, 35, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(lblTotalVendasRegistraPesquisa)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(lblValorTotalVendaPesquisa))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblQuantidadeVendaRegistrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblQuantidadeVendaRegistrada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblTotalVenda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        BuscarTodasVendas();
        lblTotalVendasRegistraPesquisa.setText("0");
        lblValorTotalVendaPesquisa.setText("0");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      BuscarQuantidadeTodasVendasPesquisa();
      BuscarTotalTodasVendasPesquisa();
      BuscarParaTabelaTodasVendasPesquisa();
    }//GEN-LAST:event_jButton1ActionPerformed
   
    private void BuscarTotalTodasVendas(){
      
          String sql = "select sum(valor_total) from venda";
       try {
                pst = conec.prepareStatement(sql);
                rs = pst.executeQuery();
             if(rs.next()){
             lblTotalVenda.setText(rs.getString(1));
             }
            }catch(SQLException e) {
            JOptionPane.showMessageDialog(null,e.getMessage(),"Aviso sql Relatorio",JOptionPane.ERROR_MESSAGE);
            }
       }
     private void BuscarParaTabelaTodasVendasPesquisa(){
      
          String sql = "select * from venda where data_venda >= ? and data_venda <= ?";
       try {
               ant = jDateInicial.getDate();
                depois = jDateFinal.getDate();
                pst = conec.prepareStatement(sql);
                pst.setDate(1,java.sql.Date.valueOf(new SimpleDateFormat("yyyy-MM-dd").format(ant)));
                pst.setDate(2,java.sql.Date.valueOf(new SimpleDateFormat("yyyy-MM-dd").format(depois)));
                rs = pst.executeQuery();
              tbVendas.setModel(DbUtils.resultSetToTableModel(rs));
            }catch(SQLException e) {
            JOptionPane.showMessageDialog(null,e.getMessage(),"Aviso sql Relatorio",JOptionPane.ERROR_MESSAGE);
            }
       } 
    private void BuscarTotalTodasVendasPesquisa(){
      
          String sql = "select sum(valor_total) from venda where data_venda >= ? and data_venda <= ?";
       try {
               ant = jDateInicial.getDate();
                depois = jDateFinal.getDate();
                pst = conec.prepareStatement(sql);
                pst.setDate(1,java.sql.Date.valueOf(new SimpleDateFormat("yyyy-MM-dd").format(ant)));
                pst.setDate(2,java.sql.Date.valueOf(new SimpleDateFormat("yyyy-MM-dd").format(depois)));
                rs = pst.executeQuery();
             if(rs.next()){
             lblValorTotalVendaPesquisa.setText(rs.getString(1));
             }
            }catch(SQLException e) {
            JOptionPane.showMessageDialog(null,e.getMessage(),"Aviso sql Relatorio",JOptionPane.ERROR_MESSAGE);
            }
       }  
     private void BuscarQuantidadeTodasVendasPesquisa(){
      
          String sql = "select count(codigo) from venda where data_venda >= ? and data_venda <= ?";
       try {
                ant = jDateInicial.getDate();
                depois = jDateFinal.getDate();
                pst = conec.prepareStatement(sql);
                pst.setDate(1,java.sql.Date.valueOf(new SimpleDateFormat("yyyy-MM-dd").format(ant)));
                pst.setDate(2,java.sql.Date.valueOf(new SimpleDateFormat("yyyy-MM-dd").format(depois)));
                rs = pst.executeQuery();
             if(rs.next()){
             lblTotalVendasRegistraPesquisa.setText(rs.getString(1));
             }
            }catch(SQLException e) {
            JOptionPane.showMessageDialog(null,e.getMessage(),"Aviso sql Relatorio",JOptionPane.ERROR_MESSAGE);
            }
       }  
    private void BuscarQuantidadeTodasVendas(){
      
          String sql = "select count(codigo) from venda";
       try {
                pst = conec.prepareStatement(sql);
                rs = pst.executeQuery();
             if(rs.next()){
             lblQuantidadeVendaRegistrada.setText(rs.getString(1));
             }
            }catch(SQLException e) {
            JOptionPane.showMessageDialog(null,e.getMessage(),"Aviso sql Relatorio",JOptionPane.ERROR_MESSAGE);
            }
       }  
    private void BuscarTodasVendas(){
      
          String sql = "select * from venda";
       try {
                pst = conec.prepareStatement(sql);
                rs = pst.executeQuery();
             tbVendas.setModel(DbUtils.resultSetToTableModel(rs)); 
            }catch(SQLException e) {
            JOptionPane.showMessageDialog(null,e.getMessage(),"Aviso sql Relatorio",JOptionPane.ERROR_MESSAGE);
            }
       }
       private void BuscarTodasProdutosVendidos(){
      
          String sql = "select * from item_venda";
       try {
                pst = conec.prepareStatement(sql);
                rs = pst.executeQuery();
             tbProdutosVendidos.setModel(DbUtils.resultSetToTableModel(rs)); 
            }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e.getMessage(),"Aviso sql Relatorio",JOptionPane.ERROR_MESSAGE);
            }
       }
      /*private void BuscarTodasVendas(){
      
          String sql = "select sum(valor_total) from venda where data_venda >= ? and data_venda <= ?";
       try {
                ant = jDateInicial.getDate();
                depois = jDateFinal.getDate();
                pst = conec.prepareStatement(sql);
                pst = conec.prepareStatement(sql);
                pst.setDate(1,java.sql.Date.valueOf(new SimpleDateFormat("yyyy-MM-dd").format(ant)));
                pst.setDate(2,java.sql.Date.valueOf(new SimpleDateFormat("yyyy-MM-dd").format(depois)));
                rs = pst.executeQuery();
             tbVendas.setModel(DbUtils.resultSetToTableModel(rs));
               
            }catch(SQLException e) {
            JOptionPane.showMessageDialog(null,e.getMessage(),"Aviso sql Relatorio",JOptionPane.ERROR_MESSAGE);
            }
       }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendaDiaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendaDiaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendaDiaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendaDiaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VendaDiaria dialog = new VendaDiaria(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateFinal;
    private com.toedter.calendar.JDateChooser jDateInicial;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblQuantidadeVendaRegistrada;
    private javax.swing.JLabel lblTotalVenda;
    private javax.swing.JLabel lblTotalVendasRegistraPesquisa;
    private javax.swing.JLabel lblValorTotalVendaPesquisa;
    private javax.swing.JTable tbProdutosVendidos;
    private javax.swing.JTable tbVendas;
    // End of variables declaration//GEN-END:variables
}
